<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KTMCVD1" failures="1" tests="1" name="TestThree" time="0.251" errors="0" timestamp="2020-11-25T19:47:30 GMT">
  <testcase classname="com.org.controller.BaseTest" name="@AfterTest releaseThreadsAndShutDown" time="0.0">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.org.controller.BaseTest.releaseThreadsAndShutDown(BaseTest.java:65)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest releaseThreadsAndShutDown -->
  <testcase classname="com.org.controller.BaseTest" name="initiateCases" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.org.controller.BaseTest.initiateCases(BaseTest.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- initiateCases -->
</testsuite> <!-- TestThree -->
